// globals
let time = 0;
let score = 0;
let scores;
let isPlaying;

// levels

// DOMs
const wordInput = document.querySelector("#word-input");
const currentWord = document.querySelector("#current-word");
const scoreDisplay = document.querySelector("#score");
const timeDisplay = document.querySelector("#time");
const message = document.querySelector("#message");
const seconds = document.querySelector("#seconds");
const easy = document.querySelector("#easy");
const normal = document.querySelector("#normal");
const highScore = document.querySelector("#high-score");

// event listeners
document.addEventListener("DOMContentLoaded", getHighScore);
window.addEventListener("load", init);
easy.addEventListener("click", setEasy);
normal.addEventListener("click", setNormal);

function setNormal() {
  wordInput.type = "password";
  var words = wordLists.cefrB2;
}
// init game

function init() {
  console.log("init");
  // get word from json
  getWord(words);
  // start matching on word input
  wordInput.addEventListener("input", startMatch);
  // countdown
  setInterval(countdown, 1000);
  // check game status every 50ms
  setInterval(checkStatus, 50);
}

// difficulty
function setEasy() {
  wordInput.type = "text";
}

function setNormal() {
  wordInput.type = "password";
}

// start game
function startMatch() {
  if (matchWords()) {
    isPlaying = true;
    time = 4;
    getWord(words);
    wordInput.value = "";
    wordInput.style.borderColor = "#0090C6";
    seconds.classList.remove('warn-txt');
    score++;
  }
  scoreDisplay.innerHTML = score;
}
// match current word to required word
function matchWords() {
  if (wordInput.value === currentWord.innerHTML) {
    message.innerHTML = "Correct!";
    message.classList.remove("msg-hide");
    message.classList.add("msg-high");
    function fader() {
      setTimeout(function () {
        message.classList.add("msg-hide");
      }, 400);
    }
    fader();
    return true;
  } else {
    message.innerHTML = "&nbsp;";

    return false;
  }
}

// get a word function
function getWord(words) {
  // gen random index
  const randIndex = Math.floor(Math.random() * words.length);
  // output word
  currentWord.innerHTML = words[randIndex];
}

// timer
function countdown() {
  // make sure time hasnt run out
  if (time >= 1) {
    time--;
    if (time == 0) {
      isPlaying = false;
    }
  }
  // display time
  timeDisplay.innerHTML = time;
  seconds.innerHTML = time;
}

// check game status
function checkStatus() {
  if (!isPlaying && time === 0 && score > 0) {
    saveHighScore(score);
    message.classList.remove("msg-high");
    message.classList.remove("msg-hide");
    message.classList.add("msg-red");
    wordInput.style.borderColor = "#F14C4F";
    seconds.classList.add('warn-txt')
    message.innerHTML = "GAME OVER";
    score = 0;
  }
}
// save highscore to local storage
function saveHighScore(s) {
  // check for high score
  if (!localStorage.getItem("scores")) {
    scores = [s];
    highScore.innerHTML = scores;
  } else if (scores[0] > s) {
    scores = JSON.parse(localStorage.getItem("scores"));
  } else {
    scores.splice(0, 1, s);
    highScore.innerHTML = scores;
  }
  localStorage.setItem("scores", JSON.stringify(scores));
}

// recall from local storage
function getHighScore() {

  if (!localStorage.getItem("scores")) {
    scores = [];
  } else {
    scores = JSON.parse(localStorage.getItem("scores"));
    highScore.innerHTML = scores;
  }};


// words

const wordLists = [
  [
    "above",
    "across",
    "action",
    "activity",
    "actor",
    "actress",
    "add",
    "address",
    "adult",
    "advice",
    "afraid",
    "after",
    "afternoon",
    "again",
    "age",
    "ago",
    "agree",
    "air",
    "airport",
    "all",
    "also",
    "always",
    "amazing",
    "and",
    "angry",
    "animal",
    "another",
    "answer",
    "any",
    "anyone",
    "anything",
    "apartment",
    "apple",
    "April",
    "area",
    "arm",
    "around",
    "arrive",
    "art",
    "article",
    "artist",
    "as",
    "ask",
    "at",
    "August",
    "aunt",
    "autumn",
    "away",
    "baby",
    "back",
    "bad",
    "bag",
    "ball",
    "banana",
    "band",
    "bank",
    "bath",
    "bathroom",
    "be",
    "beach",
    "beautiful",
    "because",
    "become",
    "bed",
    "bedroom",
    "beer",
    "before",
    "begin",
    "beginning",
    "behind",
    "believe",
    "below",
    "best",
    "better",
    "between",
    "bicycle",
    "big",
    "bike",
    "bill",
    "bird",
    "birthday",
    "black",
    "blog",
    "blonde",
    "blue",
    "boat",
    "body",
    "book",
    "boot",
    "bored",
    "boring",
    "born",
    "both",
    "bottle",
    "box",
    "boy",
    "boyfriend",
    "bread",
    "break",
    "breakfast",
    "bring",
    "brother",
    "brown",
    "build",
    "building",
    "bus",
    "business",
    "busy",
    "but",
    "butter",
    "buy",
    "by",
    "bye",
    "cafe",
    "cake",
    "call",
    "camera",
    "can1",
    "cannot",
    "capital",
    "car",
    "card",
    "career",
    "carrot",
    "carry",
    "cat",
    "CD",
    "cent",
    "centre",
    "century",
    "chair",
    "change",
    "chart",
    "cheap",
    "check",
    "cheese",
    "chicken",
    "child",
    "chocolate",
    "choose",
    "cinema",
    "city",
    "class",
    "classroom",
    "clean",
    "climb",
    "clock",
    "close1",
    "clothes",
    "club",
    "coat",
    "coffee",
    "cold",
    "college",
    "colour",
    "come",
    "common",
    "company",
    "compare",
    "complete",
    "computer",
    "concert",
    "conversation",
    "cook",
    "cooking",
    "cool",
    "correct",
    "cost",
    "could",
    "country",
    "course",
    "cousin",
    "cow",
    "cream",
    "create",
    "culture",
    "cup",
    "customer",
    "cut",
    "dad",
    "dance",
    "dancer",
    "dancing",
    "dangerous",
    "dark",
    "date",
    "daughter",
    "day",
    "dear",
    "December",
    "decide",
    "delicious",
    "describe",
    "description",
    "design",
    "desk",
    "detail",
    "dialogue",
    "dictionary",
    "die",
    "diet",
    "difference",
    "different",
    "difficult",
    "dinner",
    "dirty",
    "discuss",
    "dish",
    "doctor",
    "dog",
    "dollar",
    "door",
    "down",
    "downstairs",
    "draw",
    "dress",
    "drink",
    "drive",
    "driver",
    "during",
    "DVD",
    "each",
    "ear",
    "early",
    "east",
    "easy",
    "eat",
    "egg",
    "eight",
    "eleven",
    "email",
    "end",
    "enjoy",
    "enough",
    "euro",
    "even",
    "evening",
    "event",
    "ever",
    "every",
    "everybody",
    "everyone",
    "everything",
    "exam",
    "example",
    "excited",
    "exciting",
    "exercise",
    "expensive",
    "explain",
    "extra",
    "eye",
    "face",
    "fact",
    "fall",
    "false",
    "family",
    "famous",
    "fantastic",
    "far",
    "farm",
    "farmer",
    "fast",
    "fat",
    "father",
    "favourite",
    "February",
    "feel",
    "feeling",
    "festival",
    "few",
    "fifteen",
    "film",
    "final",
    "find",
    "fine",
    "finish",
    "fire",
    "first",
    "fish",
    "five",
    "flight",
    "floor",
    "flower",
    "fly",
    "follow",
    "food",
    "foot",
    "football",
    "for",
    "forget",
    "form",
    "forty",
    "Friday",
    "friend",
    "friendly",
    "from",
    "front",
    "fruit",
    "full",
    "fun",
    "funny",
    "future",
    "game",
    "garden",
    "geography",
    "get",
    "girl",
    "girlfriend",
    "give",
    "glass",
    "go",
    "good",
    "goodbye",
    "grandfather",
    "grandmother",
    "grandparent",
    "great",
    "green",
    "grey",
    "group",
    "grow",
    "guess",
    "guitar",
    "gym",
    "hair",
    "half",
    "hand",
    "happen",
    "happy",
    "hard",
    "hat",
    "hate",
    "have",
    "have",
    "he",
    "head",
    "health",
    "healthy",
    "hear",
    "hello",
    "help",
    "her",
    "here",
    "hey",
    "hi",
    "high",
    "him",
    "his",
    "history",
    "hobby",
    "holiday",
    "home",
    "homework",
    "hope",
    "horse",
    "hospital",
    "hot",
    "hotel",
    "hour",
    "house",
    "how",
    "however",
    "hundred",
    "husband",
    "I",
    "ice",
    "ice",
    "idea",
    "if",
    "imagine",
    "important",
    "improve",
    "in",
    "include",
    "information",
    "interest",
    "interested",
    "interesting",
    "internet",
    "interview",
    "into",
    "introduce",
    "island",
    "it",
    "its",
    "jacket",
    "January",
    "jeans",
    "job",
    "join",
    "journey",
    "juice",
    "July",
    "June",
    "just",
    "keep",
    "key",
    "kilometre",
    "kind",
    "kitchen",
    "know",
    "land",
    "language",
    "large",
    "last1",
    "late",
    "later",
    "laugh",
    "learn",
    "leave",
    "left",
    "leg",
    "lesson",
    "let",
    "letter",
    "library",
    "lie1",
    "life",
    "light",
    "like",
    "like",
    "line",
    "lion",
    "list",
    "listen",
    "little",
    "live1",
    "local",
    "long1",
    "look",
    "lose",
    "lot",
    "love",
    "lunch",
    "machine",
    "magazine",
    "main",
    "make",
    "man",
    "many",
    "map",
    "March",
    "market",
    "married",
    "match",
    "May",
    "maybe",
    "me",
    "meal",
    "mean",
    "meaning",
    "meat",
    "meet",
    "meeting",
    "member",
    "menu",
    "message",
    "metre",
    "midnight",
    "mile",
    "milk",
    "million",
    "miss",
    "mistake",
    "model",
    "modern",
    "moment",
    "Monday",
    "money",
    "month",
    "more",
    "morning",
    "most",
    "mother",
    "mountain",
    "mouse",
    "mouth",
    "move",
    "movie",
    "much",
    "mum",
    "museum",
    "music",
    "must",
    "my",
    "name",
    "natural",
    "near",
    "need",
    "negative",
    "neighbour",
    "never",
    "new",
    "news",
    "newspaper",
    "next",
    "next",
    "nice",
    "night",
    "nine",
    "no",
    "nobody",
    "north",
    "nose",
    "not",
    "note",
    "nothing",
    "November",
    "now",
    "number",
    "nurse",
    "object",
    "o�clock",
    "October",
    "of",
    "off",
    "office",
    "often",
    "oh",
    "OK",
    "old",
    "on",
    "once",
    "one",
    "onion",
    "online",
    "only",
    "open",
    "opinion",
    "opposite",
    "or",
    "orange",
    "order",
    "other",
    "our",
    "out",
    "outside",
    "over",
    "own",
    "page",
    "paint",
    "painting",
    "pair",
    "paper",
    "paragraph",
    "parent",
    "park",
    "part",
    "partner",
    "party",
    "passport",
    "past",
    "pay",
    "pen",
    "pencil",
    "people",
    "pepper",
    "perfect",
    "period",
    "person",
    "personal",
    "phone",
    "photo",
    "photograph",
    "phrase",
    "piano",
    "picture",
    "piece",
    "pig",
    "pink",
    "place",
    "plan",
    "plane",
    "plant",
    "play",
    "player",
    "please",
    "point",
    "police",
    "policeman",
    "pool",
    "poor",
    "popular",
    "positive",
    "possible",
    "post",
    "potato",
    "pound",
    "practice",
    "practise",
    "prefer",
    "prepare",
    "present",
    "pretty",
    "price",
    "probably",
    "problem",
    "product",
    "programme",
    "project",
    "purple",
    "put",
    "quarter",
    "question",
    "quick",
    "quickly",
    "quiet",
    "quite",
    "radio",
    "rain",
    "read",
    "reader",
    "reading",
    "ready",
    "real",
    "really",
    "reason",
    "red",
    "relax",
    "remember",
    "repeat",
    "report",
    "restaurant",
    "result",
    "return",
    "rice",
    "rich",
    "ride",
    "right",
    "river",
    "road",
    "room",
    "routine",
    "rule",
    "run",
    "sad",
    "salad",
    "salt",
    "same",
    "sandwich",
    "Saturday",
    "say",
    "school",
    "science",
    "scientist",
    "sea",
    "second1",
    "section",
    "see",
    "sell",
    "send",
    "sentence",
    "September",
    "seven",
    "she",
    "sheep",
    "shirt",
    "shoe",
    "shop",
    "shopping",
    "short",
    "should",
    "show",
    "shower",
    "sick",
    "similar",
    "sing",
    "singer",
    "sister",
    "sit",
    "situation",
    "six",
    "skirt",
    "sleep",
    "slow",
    "small",
    "snake",
    "snow",
    "so",
    "some",
    "somebody",
    "someone",
    "something",
    "sometimes",
    "son",
    "song",
    "soon",
    "sorry",
    ",",
    "sound",
    "soup",
    "south",
    "space",
    "speak",
    "special",
    "spell",
    "spelling",
    "spend",
    "sport",
    "spring",
    "stand",
    "star",
    "start",
    "statement",
    "station",
    "stay",
    "still",
    "stop",
    "story",
    "street",
    "strong",
    "student",
    "study",
    "style",
    "subject",
    "success",
    "sugar",
    "summer",
    "sun",
    "Sunday",
    "supermarket",
    "sure",
    "sweater",
    "swim",
    "swimming",
    "table",
    "take",
    "talk",
    "tall",
    "taxi",
    "tea",
    "teach",
    "teacher",
    "team",
    "teenager",
    "telephone",
    "television",
    "tell",
    "ten",
    "terrible",
    "test",
    "text",
    "than",
    "thank",
    "thanks",
    "that",
    "the",
    "their",
    "them",
    "then",
    "there",
    "they",
    "thing",
    "think",
    "third",
    "thirteen",
    "thousand",
    "Thursday",
    "ticket",
    "time",
    "tired",
    "title",
    "to",
    "together",
    "toilet",
    "tomato",
    "tomorrow",
    "tonight",
    "too",
    "tooth",
    "topic",
    "tourist",
    "town",
    "traffic",
    "train",
    "travel",
    "tree",
    "trip",
    "trousers",
    "true",
    "try",
    "T-shirt",
    "Tuesday",
    "turn",
    "TV",
    "twelve",
    "two",
    "umbrella",
    "uncle",
    "under",
    "understand",
    "university",
    "until",
    "up",
    "upstairs",
    "us",
    "use",
    "useful",
    "usually",
    "vacation",
    "vegetable",
    "very",
    "video",
    "village",
    "visit",
    "visitor",
    "wait",
    "waiter",
    "wake",
    "walk",
    "wall",
    "want",
    "warm",
    "wash",
    "watch",
    "water",
    "way",
    "we",
    "wear",
    "weather",
    "website",
    "Wednesday",
    "week",
    "weekend",
    "welcome",
    "well",
    "west",
    "what",
    "when",
    "where",
    "which",
    "white",
    "who",
    "why",
    "wife",
    "will",
    "win",
    "window",
    "wine",
    "winter",
    "with",
    "without",
    "woman",
    "wonderful",
    "word",
    "work",
    "worker",
    "world",
    "would",
    "write",
    "writer",
    "writing",
    "wrong",
    "yeah",
    "year",
    "yellow",
    "yes",
    "yesterday",
    "yourself",
    "young",
    "your",
  ],
  ["poop3", "poop2", "poop1", "poop"],
];

var words = wordLists[0];
